---

- name: Ensure MySQL databases are present
  mysql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    state: present
  with_items: "{{ mysql_databases }}"
