---

- name: Copy .my.cnf file with root password credentials
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    mode: 0600

- name: Ensure default user is present
  mysql_user:
    name: "{{ mysql_root_username }}"
    host: "{{ mysql_root_host }}"
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  no_log: yes
