---

- name: Check if MySQL is already installed
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Specify MySQL root password before initial installation
  debconf: name='mysql-server-5.7' question='mysql-server/{{ item }}' value='{{mysql_root_password | quote}}' vtype='password'
  with_items:
    - root_password
    - root_password_again
  when: not mysql_installed.stat.exists

- name: Update apt cache if MySQL is not yet installed
  apt: update_cache=yes
  when: not mysql_installed.stat.exists

- name: Ensure MySQL Python libraries are installed
  package: name=python3-mysqldb state=present

- name: Ensure MySQL packages are installed
  package: name={{ item }} state=present
  with_items:
    - mysql-server

# Because Ubuntu starts MySQL as part of the install process, we need to stop
# mysql and remove the logfiles in case the user set a custom log file size.
- name: Prepare configuration for initial installation
  block:
    - name: Ensure MySQL is stopped after initial install
      service: name={{ __mysql_daemon }} state=stopped

    - name: Delete innodb log files created by apt package after initial install
      file: path={{ mysql_datadir }}/{{ item }} state=absent
      with_items:
        - ib_logfile0
        - ib_logfile1
  when: not mysql_installed.stat.exists
