---

- name: Ensure MySQL users are present
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    encrypted: "{{ item.encrypted | default('yes') }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mysql_users }}"
  no_log: yes
